### ISSUE TITLE
The csv-to-api-json export should not include unpublished collections

### ISSUE THREAD

**Issue by anjackson** [ukwa/python-w3act#31]
The current `csv-to-api-json` includes collections where `"publish": false,`. As this is intended for the public API, we should exclude those and only export if `publish` is `true`.

__EDIT__ As discussed, probably makes sense to provide a command-line option to control this behaviour.

**Comment by anjackson** [comment]
Note that the current exports currently filter our unpublished collections independently: https://github.com/ukwa/python-w3act/search?q=col%5B%27publish%27%5D 

So it's probably better to make this the default and avoid repeating ourselves.

**Comment by anjackson** [comment]
Note that the only place this code is used in production is in populating the Solr collections ([here](https://github.com/ukwa/python-w3act/blob/88b2cb9953a3fdd49d7d74c0d3d1ae3f9f126ee1/w3act/dbc/generate/collections_solr.py#L9)).

That is difficult to test, so perhaps we need to discuss possible testing strategies. e.g. testing the filtering as a separate unit.

**Comment by ldbiz** [comment]
Yes, thanks, I went down a bit of a rabbit hole for a couple of days attempting to test it; the state of play is that the code has been updated (since the earlier "publish" work) to prepare the collections for the other tools, but only to the point now of confirming they successfully trigger as before. I can submit the PR on that basis, perhaps after discussion later?

**Comment by anjackson** [comment]
Yes, that sounds good.
